#!/bin/sh
# Snapshot the public members of multivar's ordinary API surface.
#
# The snapshot is a pre-release stand-in for binary-compatibility checking. It
# is not a compatibility guarantee; it is a diff that makes an intended or
# accidental change to the ordinary surface visible during review. Once a
# release exists, MiMa supersedes it.
#
# Usage:
#   tools/public-surface.sh          # fail if the committed snapshot is stale
#   tools/public-surface.sh --check  # same
#   tools/public-surface.sh --update # rewrite the committed snapshot
#
# Requires compiled JVM classes: run `sbt coreJVM/compile` first. Only the JVM
# build is inspected. All snapshotted types come from `shared` sources, so the
# Scala.js surface is the same and would add nothing but a second copy.

set -eu

mode="${1:---check}"
case "$mode" in
  --check|--update) ;;
  *)
    echo "usage: tools/public-surface.sh [--check|--update]" >&2
    exit 2
    ;;
esac

root="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
classes_list="$root/tools/public-surface/surface-classes.txt"
snapshot="$root/tools/public-surface/ordinary-api.txt"

scala_version="$(
  grep -E '^ThisBuild / scalaVersion' "$root/build.sbt" |
    head -n 1 |
    cut -d'"' -f2
)"
if [ -z "$scala_version" ]; then
  echo "could not read ThisBuild / scalaVersion from build.sbt" >&2
  exit 1
fi

classes="$root/modules/core/jvm/target/scala-$scala_version/classes"
if [ ! -d "$classes" ]; then
  echo "no compiled classes at $classes; run 'sbt coreJVM/compile' first" >&2
  exit 1
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
generated="$work/generated"

# Every javap failure below is read as "this type is gone". Confirm once, up
# front, that javap itself works, so a broken toolchain is not reported as a
# stale surface list.
if ! javap -public -classpath "$classes" multivar.core.MultivarError > /dev/null 2>&1; then
  echo "javap could not read $classes" >&2
  javap -public -classpath "$classes" multivar.core.MultivarError >&2 || true
  exit 1
fi

{
  echo "# Public surface of the ordinary multivar API."
  echo "#"
  echo "# Generated by tools/public-surface.sh from the JVM build. Do not edit by"
  echo "# hand; run 'tools/public-surface.sh --update'."
  echo "#"
  echo "# Members are sorted rather than listed in declaration order, so the file is"
  echo "# stable across compiler versions. Three groups of mechanically derived"
  echo "# members are omitted so that a diff shows intent rather than noise:"
  echo "#"
  echo "#   * case-class and object boilerplate: productArity, productPrefix,"
  echo "#     productElement, productElementName, productElementNames,"
  echo "#     productIterator, canEqual, equals, hashCode, toString, fromProduct,"
  echo "#     copy\$default\$N, MODULE\$, and the static initializer;"
  echo "#   * positional _N accessors, which restate the named field accessors while"
  echo "#     the apply and copy signatures already record the full field list;"
  echo "#   * a companion object whose members are all reachable as static"
  echo "#     forwarders on the class of the same name;"
  echo "#   * Scala synthetic accessors whose names contain \$\$;"
  echo "#   * members that mention SpectralCore, which exists only as a Scaladoc"
  echo "#     workaround for package-private constructor parameters and is not"
  echo "#     part of the ordinary analyst surface."
  echo "#"
  echo "# A synthesized apply, copy, or unapply IS listed. Those are what let a"
  echo "# caller construct a fitted result that never came out of a fit, so they"
  echo "# belong in any review of the surface."
} > "$generated"

# javap reads the constant pool and prints type names without resolving them, so
# only the multivar class directory is needed on the classpath, not Gale.
javap_body() {
  javap -public -classpath "$classes" "$1" > "$work/raw" 2>/dev/null || return 1
  [ -s "$work/raw" ] || return 1
  grep -v '^Compiled from' "$work/raw" > "$work/body"
}

normalize_members() {
  grep -v '^}' |
    grep -vE '(productIterator|productElementNames|productArity|productPrefix|productElement|productElementName|canEqual|hashCode|equals|toString|fromProduct)\(' |
    grep -v 'copy[$]default[$]' |
    grep -v 'MODULE[$]' |
    grep -vE 'public static \{\};' |
    grep -vE ' _[0-9]+\(\);$' |
    grep -v '[$][$]' |
    grep -v 'SpectralCore' |
    sed 's/^[[:space:]]*//' |
    LC_ALL=C sort
}

# A member reachable as a static forwarder on the class and as an instance
# method on the companion is one member. Comparing the two needs `static`
# elided, and also a leading type-parameter clause, which javap prints on the
# forwarder but sometimes erases on the companion's own method.
forwarder_key() {
  sed -e 's/^public static /public /' -e 's/^public <[^<>]*> /public /' "$1" |
    LC_ALL=C sort -u
}

emit() {
  {
    echo ""
    cat "$1"
    sed 's/^/  /' "$2"
    echo "}"
  } >> "$generated"
}

missing=""
while IFS= read -r entry; do
  case "$entry" in
    ''|\#*) continue ;;
  esac

  has_class=0
  if javap_body "$entry"; then
    has_class=1
    head -n 1 "$work/body" > "$work/class_decl"
    tail -n +2 "$work/body" | normalize_members > "$work/class_members"
  fi

  has_companion=0
  if javap_body "$entry\$"; then
    has_companion=1
    head -n 1 "$work/body" > "$work/companion_decl"
    tail -n +2 "$work/body" | normalize_members > "$work/companion_members"
  fi

  if [ "$has_class" -eq 0 ] && [ "$has_companion" -eq 0 ]; then
    missing="$missing $entry"
    continue
  fi

  if [ "$has_class" -eq 1 ]; then
    emit "$work/class_decl" "$work/class_members"
  fi

  if [ "$has_companion" -eq 1 ]; then
    if [ "$has_class" -eq 0 ]; then
      emit "$work/companion_decl" "$work/companion_members"
    else
      forwarder_key "$work/class_members" > "$work/class_key"
      forwarder_key "$work/companion_members" > "$work/companion_key"
      comm -13 "$work/class_key" "$work/companion_key" > "$work/companion_only"
      if [ -s "$work/companion_only" ]; then
        emit "$work/companion_decl" "$work/companion_members"
      fi
    fi
  fi
done < "$classes_list"

if [ -n "$missing" ]; then
  echo "no compiled class found for:$missing" >&2
  echo "the surface list names a type that no longer exists; update surface-classes.txt" >&2
  exit 1
fi

if [ "$mode" = "--update" ]; then
  cp "$generated" "$snapshot"
  echo "public surface snapshot updated: $snapshot"
  exit 0
fi

if [ ! -f "$snapshot" ]; then
  echo "no committed snapshot at $snapshot; run 'tools/public-surface.sh --update'" >&2
  exit 1
fi

if diff -u "$snapshot" "$generated"; then
  echo "public surface: unchanged"
else
  echo "" >&2
  echo "the ordinary public surface changed. If the change is intended, run" >&2
  echo "'tools/public-surface.sh --update' and review the diff as part of the change." >&2
  exit 1
fi
